version: 2.1

jobs:
  release:
    docker:
      - image: python:3.8-buster
    steps:
      - checkout

      - run:
          name: Install Python packages
          command: pip install --progress-bar off -r requirements.txt

      - run:
          name: Install Python build/publishing tools
          command: pip install build==0.7.0 twine==3.7.0

      - run:
          name: Package
          command: VERSION=${CIRCLE_TAG:1} python setup.py bdist_wheel

      - run:
          name: Release
          command: >
            python -m twine upload --repository-url "${PYPI_REPO_URL}"
            --username "${PYPI_REPO_USERNAME}"
            --password "${PYPI_REPO_PASSWORD}"
            dist/*
workflows:
  version: 2
  build:
    jobs:
      - release:
          context: pypi-repo
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(.+)/